### ISSUE TITLE
Get multiple list entries without knowing the id

### ISSUE THREAD

**Issue by capiman** [CESNET/rousette#16]
I am trying something similar to

https://stackoverflow.com/questions/56124918/is-it-legal-to-get-all-list-instances-in-restconf

This is only an example!
Assume a given vehicle is carrying zero to multiple plants. Silly I know, but only for description purposes.

```
{
  "transport:vehicle": {
....
  },
  "transport:plant": [
    {
      "uniqueid": "abc",
...
    },
  "transport:plant": [
    {
      "uniqueid": "def",
...
    },
  "transport:plant": [
    {
      "uniqueid": "ghi",
...
    }
}
```

I can do a GET request and get all the data (vehicle info and possible plants).

URL /restconf/ds/ietf-datastores:running/

I can do a GET request for the vehicle info

URL /restconf/ds/ietf-datastores:running/transport:vehicle

I *cannot* do a GET request for the all available plants info (ERROR CASE?)

URL /restconf/ds/ietf-datastores:running/transport:plant

Rousette tells me "error-message": "List '/transport:plant' requires 1 keys"
But is this really the case, or shall it return all plants according to above question on stack overflow?

(Note aside: keys -> key, but does not matter, perhaps case for 2 keys possible???)

I can do a GET request for a certain plant info, when I know the uniqueid.

URL /restconf/ds/ietf-datastores:running/transport:plant="abc"

But usually I do not know the uniqueid before querying all entries.

I am interested in "ERROR CASE?" (above):
My rousette sources are not the latest up-to-date ones, perhaps meanwhile fixed?
Or error or not (yet?) supported? Or other way to do this?

Yang for example:

```
module transport {
  namespace "http://transport.notusedtestdomain.de/";
  prefix transportprefix;

  container vehicle {
    leaf info {
      type string;
    }
    leaf anotherinfo {
      type string;
    }
  }
  list plant {
    key "uniqueid";
    leaf uniqueid {
      type string;
    }
    leaf info {
      type string;
    }
    leaf anotherinfo {
      type string;
    }
  }
}
```

**Comment by jktjkt** [comment]
I think that the feature that you’re looking for is not allowed by RFC8040. The GET operation works on “all resource types except (…)”, but you won’t find any resource definition which corresponds to an “entire list”. As a result, there are no RESTCONF operations which would allow working on an entire list (or leaf-list). It’s a silly limitation if you ask me, but we care about standard compliance and we won’t be adding a non-standard feature like this.

However, if you can offer some pointers to RFCs or errata which indicate that this is actually meant to work, please reopen this bugreport.

**Comment by capiman** [comment]
Hello Jan,

many thanks for your fast reply. I got in contact with one of the authors of RESTCONF RFC and he replied:

RFC 8040:

3.5.  Data Resource

   A data resource represents a YANG data node that is a descendant node
   of a datastore resource.  Each YANG-defined data node can be uniquely
   targeted by the request-line of an HTTP method.  Containers, leafs,
   leaf-list entries, list entries, anydata nodes, and anyxml nodes are
   data resources.

There are also examples in the RFC indicating how you can retrieve a
nested structure (which I think is your question).

RFC 8527 introduces additional RESTCONF resources that give you even
more control over the data you are accessing. I have no idea whether
NMDA is implemented in the tool you are using.

Could this be helpful to clarify the issue?

Many thanks!

Best regards,
Martin

**Comment by capiman** [comment]
Got another clarification/hint:

If I understand the question correctly, you are asking to target the YANG ‘list’ node directly.

RFC 8040 doesn’t allow this, but [the list-pagination extension for RESTCONF](https://datatracker.ietf.org/doc/html/draft-ietf-netconf-list-pagination-rc) will.

**Comment by jktjkt** [comment]
Yes, this is the key (emphasis mine):

> A data resource represents a YANG data node that is a descendant node of a datastore resource. Each YANG-defined data node can be uniquely targeted by the request-line of an HTTP method. Containers, leafs, leaf-list **entries**, list **entries**, anydata nodes, and anyxml nodes are data resources.

As this snippet of the RFC shows, you can address one list *entry*. It doesn't explicitly say "you cannot address an entire list", but since the spec doesn't define any other resource which would correspond to "all list entries", the conclusion is that you cannot operate on a list as a whole.

That said, you might hack this around by using the [`fields`](https://datatracker.ietf.org/doc/html/rfc8040#section-4.8.3) query parameter which Rousette supports. I don't think we have a test case explicitly for retrieval of an entire list, but from the top of my head this "should" work. Your example is a bit complicated because it's a top-level list, so it's probably going to require something like:
```
GET /restconf/ds/ietf-datastores:running&fields=transport:plant
```
If you test this, does it happen to work?

I agree that the list pagination draft is obviously a much better way, and keep in mind that while Rousette supports this feature, it's still something that's *optional* in RESTCONF, and therefore other servers might not implement it at all.

I've also added an answer to the stackoverflow question.
