### ISSUE TITLE
Can't find PAM

### ISSUE THREAD

**Issue by choppsv1** [CESNET/rousette#9]
I'm trying to build on ubuntu 22.04.. and I cannot figure out what libpam package i need to install so that cmake finds the "pam" module. Ubuntu seems to fully support install pam and a libpam0g-dev pacakge so I'm not sure what else to do. I'd really like to not be installing PAM from source.

Any guidance here?

**Comment by peckato1** [comment]
Hello,

It seems that `libpam0g-dev` 1.4.0 in ubuntu 22.04 is missing the pkgconfig (`.pc`) file, so the CMake can't find the package. I took a look in ubuntu 23.10 and the `libpam0g-dev` (1.5.2) is there so the project should configure correctly.

(If [this](https://github.com/linux-pam/linux-pam/commit/b4f0e2e1f7a18169938eedeff8180e0c75473bb5) is correct, then the pkgconfig file was not even distributed by libpam before versions 1.5.2.)

**Comment by jktjkt** [comment]
I'm afraid that @peckato1 is correct and that upstream only started providing pkg-config files three years ago in 1.5.2. We never hit this because our CI as well as the developers' machines have pretty recent versions of these packages.

I tried to find out if it's possible to override this at the CMakeLevel (like a bunch of `-DLIBPAM_INCLUDE_DIR=... -DLIBPAM_LIBRARIES=...`),but it seems that there's no such way. You could always "workaround" this by creating a stub `.pc` file yourself, but I understand that this is ugly from the building PoV.

If you need to support older platforms and if the patch is reasonably self-contained, patches welcome, I'll be happy to merge it. However, since there's a more recent Ubuntu LTS which has this issue fixed already, we won't be actively writing patches to make this happen.
